# Generated by Django 5.0.1 on 2024-01-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='./images/meeple.jpg', max_length=500),
        ),
    ]
