# Generated by Django 5.0.1 on 2024-01-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, default='./images/meeple.jpg', max_length=500),
        ),
    ]
