# Generated by Django 5.0.1 on 2024-01-13 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
