# Generated by Django 5.0.1 on 2024-01-12 21:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(related_name='board_games', to='genres.genre')),
                ('reviews', models.ManyToManyField(related_name='board_games', to='reviews.review')),
            ],
        ),
    ]
