# Generated by Django 5.0.1 on 2024-01-12 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0001_initial'),
        ('games_owned', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='owned_by',
            field=models.ManyToManyField(related_name='games_owned', through='games_owned.GameOwned', to=settings.AUTH_USER_MODEL),
        ),
    ]
