# Generated by Django 5.0.1 on 2024-01-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0004_alter_boardgame_reviews'),
        ('reviews', '0006_alter_review_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='games_reviewed', to='reviews.review'),
        ),
    ]
