# Generated by Django 5.0.1 on 2024-01-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0005_alter_boardgame_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='reviews',
        ),
    ]
