# Generated by Django 5.0.1 on 2024-01-13 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOwned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board_games.boardgame')),
            ],
        ),
    ]
