# Generated by Django 5.0.1 on 2024-01-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0006_remove_boardgame_reviews'),
        ('reviews', '0006_alter_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='board_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='board_games.boardgame'),
            preserve_default=False,
        ),
    ]
